version: '2'
services:
    jhipsterprueba1-app:
        image: jhipsterprueba1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterprueba1-mysql:3306/jhipsterprueba1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterprueba1-mysql:
        extends:
            file: mysql.yml
            service: jhipsterprueba1-mysql
